[build]
  command = "npm run build"
  publish = "dist/schnittstellenpass/browser"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-angular-universal"

[functions]
  node_bundler = "esbuild"
